services:
  - type: web
    name: tribute-arcade
    runtime: node
    plan: free
    rootDir: outputs
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
